groups/urls.py
from django.urls import path,include
from . import views
from . import forms

app_name = 'groups'

urlpatterns = [
    path('', views.GroupList.as_view(),name='list'),
    path('create/', views.CreateGroup.as_view(),name='create'),
    path('mygroups/',views.UserGroupList.as_view(),name='mygroups'),
    path('<slug>/', views.GroupDetail.as_view(),name='detail'),
    path('join/<slug>/', views.JoinGroup.as_view(),name='join'),
    path('leave/<slug>', views.LeaveGroup.as_view(),name='leave'),
]

posts/urls.py
from django.urls import path,include
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='list'),
    path('post/new/',views.CreatPost.as_view(),name='create'),
    path('post/delete/<int:pk>',views.DeletePost.as_view(),name='delete'),
    # path('post/<username>/<int:pk>',views.PostDetail.as_view(),name='detail'),
    path('posts/<username>/',views.UserPostList.as_view(),name='user_post'),
]

social_media/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls',namespace='posts')), 
    path('accounts/', include('accounts.urls',namespace='accounts')), 
    path('accounts/', include('django.contrib.auth.urls')), 
    path('groups/', include('groups.urls',namespace='groups')), 
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/',include(debug_toolbar.urls))
    ] + urlpatterns

groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.

class Group(models.Model):
    name = models.CharField(max_length=256,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    members = models.ManyToManyField(User,through='GroupMembership')
    
    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name
    
    def save(self,*arg,**kwargs):
        self.slug = slugify(self.name)
        # /claire peng --> /claire-peng
        super().save(*arg,**kwargs)
    
    def get_absolute_url(self):
        return reverse('groups:detail', kwargs={'slug':self.slug})
        

class GroupMembership(models.Model):
    group = models.ForeignKey(Group,related_name='membership',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='membership',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    
    class Meta:
        unique_together = ('group','user')
    

groups/forms.py
from django import forms
from . import models

class GroupForm(forms.ModelForm):

    class Meta():
        model = models.Group
        fields = ('name','description')

groups/views.py
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render
from django.contrib.auth.mixins import (LoginRequiredMixin, 
                                        PermissionRequiredMixin)

from django.urls import reverse
from django.views import generic
from . import models
from . import forms
from braces.views import SelectRelatedMixin,PrefetchRelatedMixin
from django.shortcuts import get_object_or_404,redirect
from django.contrib import messages
from django.db import IntegrityError
from django.http import Http404
from django.core.exceptions import ObjectDoesNotExist


from django.contrib.auth import get_user_model
User = get_user_model()


# Create your views here.
class CreateGroup(LoginRequiredMixin,generic.CreateView):
    model = models.Group
    form_class = forms.GroupForm

class UserGroupList(LoginRequiredMixin,PrefetchRelatedMixin,generic.ListView):
    # groups belonging to an user
    model = models.Group
    prefetch_related = ('members','posts',)
    template_name = 'groups/mygroups.html'
    context_object_name = 'mygroups'
    
    def get_queryset(self):
        return super().get_queryset().filter(members__username__iexact=self.request.user)

class GroupDetail(PrefetchRelatedMixin,generic.DetailView):
    model = models.Group
    prefetch_related = ('members','posts')

class GroupList(PrefetchRelatedMixin,generic.ListView):
    model = models.Group
    prefetch_related = ('members','posts')
    

class JoinGroup(LoginRequiredMixin,generic.RedirectView):
    
    # Once joining the group, you will be directed to the group detail page
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:detail',kwargs={'slug':kwargs.get('slug')})
        # use .get when you want to get only one object
        

    # Make sure the group exists
    def get(self, request, *args, **kwargs):

        group = get_object_or_404(models.Group,slug=kwargs.get('slug'))
    
        try:
            models.GroupMembership.objects.create(
                user=request.user,
                group=group
            )

        except IntegrityError:
            messages.warning(request,'You are already a member!')
        
        else:
            messages.success(request,'Joined the group!')    
        
        return super().get(request,*args,**kwargs)

class LeaveGroup(LoginRequiredMixin,generic.RedirectView):
    
    # Once joining the group, you will be directed to the group detail page
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:detail',kwargs={'slug':kwargs.get('slug')})
    
    # Make sure the group exists
    def get(self, request, *args, **kwargs):

        try:
            membership = models.GroupMembership.objects.get(
            user= self.request.user,
            group__slug=self.kwargs.get('slug')
            )

        except models.GroupMembership.DoesNotExist:
            messages.warning(request,'You aren\'t a group member')
        
        else:
            membership.delete()
            messages.success(request,'Left the group!')
        
        return super().get(request,*args,**kwargs)

groups/templates/groups/group_base.html
{% extends 'base.html' %}

{% block title %}Create Group{% endblock %}

{% block content %}
<div class='container content group-page'>
    {% block pre_group %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block post_group %}{% endblock %}
</div>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block title %}Group Details{% endblock %}

{% block pre_group %}
<h1 class='page-title'>{{ group.name }}</h1>
<h4 class='member-count'>{{ group.members.count}} member{{ group.members.count|pluralize }}</h4>
<div class="content">
    {% if user in group.members.all %}
    <a type='button' class='btn btn-warning' href="{% url 'groups:leave' slug=group.slug %} "><span
            class='glyphicon glyphicon-remove-circle'>Leave</span></a>

    {% else %}
    <a type='button' class='btn btn-primary' href="{% url 'groups:join' slug=group.slug %}"><span
            class='glyphicon glyphicon-ok-circle'>Join</span></a>
    {% endif %}
</div>
{% endblock %}

{% block group_content %}

<div class='group-detail'>

    {% if group.posts.count == 0 %}
    <h2>No posts in this group yet!</h2>

    {% else %}

    {% for post in group.posts.all %}
    {% include 'posts/_post.html' %}
    <!-- _post.html: means its supposed to be injected into other html files -->
    {% endfor %}

    {% endif %}
</div>
{% endblock %}

{% block post_group %}{% endblock %}

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Group Details{% endblock %}

{% block pre_group %}
<h1 class='page-title'>Create Group</h1>
{% endblock %}

{% block group_content %}
<form action="{% url 'groups:create' %}" method="POST" class='group-create-form'>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class='btn btn-primary btn-large'>Create</button>
</form>
{% endblock %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block title %}Group Details{% endblock %}

{% block pre_group %}
<div class='pre-group'>
    {% if user.is_authenticated %}
    <a class='btn btn-primary' href="{% url 'groups:create' %}">Create New Group</a>
    {% endif %}
    <h1 class='page-title'>Groups</h1>
    <p>Welcome to Groups page</p>
</div>
{% endblock %}

{% block group_content %}
<div class='group-list'>

    {% for group in group_list %}
    <h2 class='group-list-title'>
        <a href=" {% url 'groups:detail' slug=group.slug %}">{{ group.name }}</a>
    </h2>
    <p class='group-list-description'> {{ group.description|truncatewords:200 }}</p>
    <div class='row'>
        <div class="col-md-2  group-list-footer">
            <span class='badge'>{{ group.members.count }}</span>
            member{{ group.members.count|pluralize }}
        </div>

        <div class="col-md-2 group-list-footer">
            <span class='badge'>{{ group.posts.count }}</span>
            post{{ group.posts.count|pluralize }}
        </div>
    </div>
    <hr>
    {% endfor %}
</div>
{% endblock %}

{% block post_group %}{% endblock %}

groups/templates/groups/mygroups.html
{% extends 'groups/group_base.html' %}

{% block title %}Your Groups{% endblock %}

{% block pre_group %}
<div class='pre-group'>
    {% if user.is_authenticated %}
    <a class='btn btn-primary' href="{% url 'groups:create' %}">Create New Group</a>
    {% endif %}
    <h1 class='page-title'>My Groups</h1>
</div>
{% endblock %}

{% block group_content %}
{% for group in mygroups %}
<div class='group-list'>
    <h2 class='group-list-title'>
        <a href=" {% url 'groups:detail' slug=group.slug %}">{{ group.name }}</a>
    </h2>
    <p class='group-list-description'> {{ group.description|truncatewords:200 }}</p>
    <div class='row'>
        <div class="col-md-2  group-list-footer">
            <span class='badge'>{{ group.members.count }}</span>
            member{{ group.members.count|pluralize }}
        </div>
        <div class="col-md-2 group-list-footer">
            <span class='badge'>{{ group.posts.count }}</span>
            post{{ group.posts.count|pluralize }}
        </div>
    </div>
    <hr>
</div>
{% endfor %}
{% endblock %}

{% block post_group %}{% endblock %}