accounts/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views
from . import forms

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUp.as_view(),name='signup'),
    path('login/', auth_views.LoginView.as_view(form_class=forms.UserLoginForm),name='login'),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'),
]

groups/urls.py
from django.urls import path,include
from . import views
from . import forms

app_name = 'groups'

urlpatterns = [
    path('', views.GroupList.as_view(),name='list'),
    path('create/', views.CreateGroup.as_view(),name='create'),
    path('mygroups/',views.UserGroupList.as_view(),name='mygroups'),
    path('<slug>/', views.GroupDetail.as_view(),name='detail'),
    path('join/<slug>/', views.JoinGroup.as_view(),name='join'),
    path('leave/<slug>', views.LeaveGroup.as_view(),name='leave'),
]

posts/urls.py
from django.urls import path,include
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='list'),
    path('post/new/',views.CreatPost.as_view(),name='create'),
    path('post/delete/<int:pk>',views.DeletePost.as_view(),name='delete'),
    # path('post/<username>/<int:pk>',views.PostDetail.as_view(),name='detail'),
    path('posts/<username>/',views.UserPostList.as_view(),name='user_post'),
]

social_media/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls',namespace='posts')), 
    path('accounts/', include('accounts.urls',namespace='accounts')), 
    path('accounts/', include('django.contrib.auth.urls')), 
    path('groups/', include('groups.urls',namespace='groups')), 
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/',include(debug_toolbar.urls))
    ] + urlpatterns

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width" , initial-scale="1.0">
    <title>{% block title %}title{% endblock %}</title>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>


    <!-- Bootstrap CSS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Medium Style Editor-->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css"
        type="text/css" media="screen" charset="utf-8">

    <!-- Custom CSS-->
    <link rel="stylesheet" href="{% static 'css/master.css' %}" />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light navbar-font">
        <div class="container navbar-container">
            <ul class="navbar-nav">
                <li><a class="navbar-brand" href="{% url 'posts:list' %}">Star Social</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </li>
            </ul>

            <!-- <div class="collapse navbar-collapse" id="navbarSupportedContent"> -->

            <ul class="navbar-nav navbar-right">

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:create' %}">Post</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'groups:list' %}">Groups</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'groups:create' %}">Create Group</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'groups:mygroups' %}">My
                            Groups</a>
                        <a class="dropdown-item" href="{% url 'posts:user_post' username=user.username %}">My Posts</a>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'groups:list' %}">Groups</a>
                </li>
                <li><a class="nav-link" href="{% url 'accounts:login' %}">Log in</a></li>
                <li><a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>
                {% endif %}
            </ul>
            <!-- </div> -->
        </div>
    </nav>

    <!-- Content -->

    <div class='container-fluid content'>
        <div class='messages'>
            {% if messages %}
            {% for message in messages %}
            <div class="toast" id="myToast" data-delay="2000" style="position: absolute; bottom: 1.5rem; left: 2rem" ;>
                <div class="toast-header toast-{{message.tags}}">
                    <div class="toast-body">
                        {{ message }}
                    </div>
                </div>
                <!-- <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div> -->
                {% endfor %}
                {% endif %}
            </div>
            <div class='row'>
                <div class='col-md-8 mx-auto'>
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
</body>



<!-- Javascript -->
<script type="text/javascript" src="{% static 'js/master.js' %}"></script>
</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block title %}Home Page{% endblock %}

{% block content %}
<h1>Hello There</h1>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block title %}Thanks{% endblock %}

{% block content %}
<h1>You are logged out. Thanks for visiting.</h1>
{% endblock %}