groups/urls.py
from django.urls import path,include
from . import views
from . import forms

app_name = 'groups'

urlpatterns = [
    path('', views.GroupList.as_view(),name='list'),
    path('create/', views.CreateGroup.as_view(),name='create'),
    path('mygroups/',views.UserGroupList.as_view(),name='mygroups'),
    path('<slug>/', views.GroupDetail.as_view(),name='detail'),
    path('join/<slug>/', views.JoinGroup.as_view(),name='join'),
    path('leave/<slug>', views.LeaveGroup.as_view(),name='leave'),
]

posts/urls.py
from django.urls import path,include
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='list'),
    path('post/new/',views.CreatPost.as_view(),name='create'),
    path('post/delete/<int:pk>',views.DeletePost.as_view(),name='delete'),
    # path('post/<username>/<int:pk>',views.PostDetail.as_view(),name='detail'),
    path('posts/<username>/',views.UserPostList.as_view(),name='user_post'),
]

social_media/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls',namespace='posts')), 
    path('accounts/', include('accounts.urls',namespace='accounts')), 
    path('accounts/', include('django.contrib.auth.urls')), 
    path('groups/', include('groups.urls',namespace='groups')), 
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/',include(debug_toolbar.urls))
    ] + urlpatterns

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from  django.utils import timezone
import misaka
from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts',on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group,related_name='posts',on_delete=models.CASCADE)

    def __str__(self):
        return self.message
    
    def save(self,*args,**kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args,**kwargs)
    
    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'username':self.user.username,
                                               'pk': self.pk})
    class Meta:
        ordering = ['-created_at']
        unique_together = [('user','message')]

posts/forms.py
from django import forms
from . import models

class PostForm(forms.ModelForm):
    
    class Meta():
        model = models.Post
        fields = ('message','group')

posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.http import Http404
from django.shortcuts import get_object_or_404,redirect

from braces.views import SelectRelatedMixin,PrefetchRelatedMixin
from . import models
from . import forms
from django.contrib import messages


from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.

class PostList(SelectRelatedMixin,generic.ListView):
    # posts belonging to a group
    model = models.Post
    select_related = ('user','group')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['user_groups'] = models.Group.objects.filter(members__in=[self.request.user])
        # context['other_groups'] = models.Group.objects.exclude(members__in=[self.request.user])
        return context

class UserPostList(LoginRequiredMixin,SelectRelatedMixin,generic.ListView):
    # posts belonging to one user
    model = models.Post
    select_related = ('user','group')
    template_name = 'posts/user_post_list.html'
    context_object_name = 'user_post_list'

    def get_queryset(self):
        post_user = get_object_or_404(User,username=self.kwargs.get('username'))
        qs = super().get_queryset()
        return qs.filter(user__username=post_user.username)

    # if you want to redirect when the object doesnot exist
    # def get(self, request, *args, **kwargs):
        
    #     post_user = self.get_queryset()
        
    #     if not post_user:
    #         messages.warning(request,'The member does not exist')
    #         return redirect('posts:list')
        
    #     return super().get(request,*args,**kwargs)

    

class CreatPost(SelectRelatedMixin,LoginRequiredMixin,generic.CreateView):
    model = models.Post
    form_class = forms.PostForm
    select_related = ('user','group')

    # TODO: https://stackoverflow.com/questions/24041649/filtering-a-model-in-a-createview-with-get-queryset
    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        group_slug = self.object.group.slug
        return reverse('groups:detail',kwargs={'slug':group_slug})
    
    
class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):

    model = models.Post
    select_related = ('user','group')
    
    def get_queryset(self):
        return super().get_queryset().filter(user__username__iexact=self.request.user.username)
        # use "self.request.user.username" if it's login required
    
    def delete(self, request, *args, **kwargs):
        messages.success(self.request,'Post Deleted!')
        return super().delete(request, *args, **kwargs)
    
    def get_success_url(self):
        group_slug = self.object.group.slug
        return reverse_lazy('groups:detail',kwargs={'slug':group_slug})

posts/templates/posts/_post.html
<div class='card card-body post-body'>
    <div class='post-username'>
        <a href="{% url 'posts:user_post' username=post.user.username %}">{{ post.user.username }}</a>
    </div>
    <div class='post-timestamp'>
        <time>{{ post.created_at | date:"M Y"  }}</time>
    </div>
    <p>{{ post.message_html | safe }}</p>

    <!-- <div class='footer'>
        {% if user.is_authenticated and post.user == user %}
        <a class='delete' href="{% url 'posts:delete' pk=post.pk %}">Delete</a>
        {% endif %}
    </div> -->
</div>

posts/templates/posts/post_base.html
{% extends 'base.html' %}

{% block title %}Create Post{% endblock %}

{% block content %}
<div class='container content post-page'>
    {% block pre_post %}{% endblock %}
    {% block post_content %}{% endblock %}
    {% block post_post %}{% endblock %}
</div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}
{% block title %}Delete Post{% endblock %}

{% block content %}
<div class='container'>
    <h5>Are you sure you want to delete the post?</h5>

    <div clsss='single-post'>
        {% include "posts/_post.html" with post=object hide_delete=True %}
    </div>

    <div class='delete-post-title'>
        <form method="POST" action="{% url 'posts:delete' pk=post.pk %}">
            {% csrf_token %}
            <button type="submit" class='btn btn-danger'>Delete</button>
            <a class='btn btn-simple' href="{% url 'groups:detail' slug=post.group.slug %}">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Create Post{% endblock %}

{% block pre_post %}
<h1 class='page-title'>Create a New Post</h1>
{% endblock %}

{% block post_content %}
<form action="{% url 'posts:create' %}" method="POST" class='post-create-form'>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class='btn btn-primary'>Create</button>
</form>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}

{% block title %}Post Lists{% endblock %}

{% block pre_post %}
<div class='pre-post'>
    {% if user.is_authenticated %}
    <a class='btn btn-primary' href="{% url 'posts:create' %}">Create New Post</a>

    <h1 class='page-title'>Your Groups</h1>
    {% for group in user_groups %}
    <div class='group-list card card-body'>
        <h2 class='group-list-title'>
            <a href=" {% url 'groups:detail' slug=group.slug %}">{{ group.name }}</a>
        </h2>
        <p class='group-list-description'> {{ group.description|truncatewords:200 }}</p>
    </div>
    {% endfor %}
    {% endif %}

    {% for post in post_list %}
    <div class='card card-body post-body'>
        <div class='post-groupname'>
            <a href="{% url 'groups:detail' slug=post.group.name %}">{{ post.group.name }}</a>
        </div>
        <div class='post-username'>
            <a href="{% url 'posts:user_post' username=post.user.username %}">{{ post.user.username }}</a>
        </div>
        <div class='post-timestamp'>
            <time>{{ post.created_at | date:"M Y"  }}</time>
        </div>
        <p>{{ post.message_html | safe }}</p>
    </div>
    {% endfor %}

    <!-- <div class='footer'>
            {% if user.is_authenticated and post.user == user %}
            <a class='delete' href="{% url 'posts:delete' pk=post.pk %}">Delete</a>
            {% endif %}
        </div> -->
</div>
{% endblock %}

{% block group_content %}

<!-- {% for post in group.posts.all %}
{% include 'posts/_post.html' %}
{% endfor %} -->

{% endblock %}

posts/templates/posts/user_post_list.html
{% extends 'posts/post_base.html' %}

{% block title %}Post Lists{% endblock %}

{% block pre_post %}
<div class='pre-post'>
    {% if user.is_authenticated %}
    <a class='btn btn-primary' href="{% url 'posts:create' %}">Create New Post</a>


    {% if user_post_list %}

    {% for post in user_post_list %}
    <div class='card card-body post-body'>
        <div class='post-groupname'>
            <a href="{% url 'groups:detail' slug=post.group.name %}">{{ post.group.name }}</a>
        </div>
        <div class='post-username'>
            <a href="{% url 'posts:user_post' username=post.user.username %}">{{ post.user.username }}</a>
        </div>
        <div class='post-timestamp'>
            <time>{{ post.created_at | date:"M Y"  }}</time>
        </div>
        <p>{{ post.message_html | safe }}</p>
    </div>
    {% endfor %}


    {% else %}
    <div class='empty-message'>
        <p>The user does not have any posts.</p>
    </div>


    {% endif %}
    {% endif %}

    <!-- <div class='footer'>
            {% if user.is_authenticated and post.user == user %}
            <a class='delete' href="{% url 'posts:delete' pk=post.pk %}">Delete</a>
            {% endif %}
        </div> -->
</div>
{% endblock %}

{% block group_content %}
{% endblock %}